Install gypsy in readthedocs instead of mock deps
with mock deps there was following error:

pygypsy.basal_area_increment (pygypsy/basal_area_increment.c:8468)
    ctypedef class numpy.dtype [object PyArray_Descr]:
    TypeError: numpy.dtype is not a type object

even with using type as a spec for the Mock it didn't work